### ISSUE TITLE
What user is the shell script run as and are there options to change?

### ISSUE THREAD

**Issue by pajtai** [ahw/vim-hooks#52]
I'm trying to do some automated builds (jade, sass, browserify), but I'm getting npm not found errors. Guessing it's because the user the script is run as is not the one that has node installed. Are there any options that can be set around the user to run the script, or does it have to be baked into the script itself?

**Comment by pajtai** [comment]
Okay, it is current user apparently.... I just really didn't have node installed - sorry :( ...... now that it is, it all works as I expected.... great plugin, thanks!

**Comment by ahw** [comment]
No worries, glad to hear you got it sorted! So far I haven't personally had
the need to change the run-as user, but if something like that comes up
again let me know, I could probably expose an option to configure it.

Andy
